# Generated by Django 5.0.1 on 2024-01-28 14:38

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_profile_identify_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz123', length=7, max_length=25, prefix=''),
        ),
    ]
