# Generated by Django 5.0.1 on 2024-01-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pid',
        ),
    ]
