# Generated by Django 5.0.1 on 2024-01-29 13:31

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelfeatures_hotelgallery_roomtype_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='hgid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=10, max_length=20, prefix='', unique=True),
        ),
    ]
