# Generated by Django 5.0.1 on 2024-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotelgallery_hgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
